export const langData = [
  { label: "C++", value: 3, color: "#f34b7d" },
  { label: "Python", value: 3, color: "#3572A5" },
  { label: "JavaScript", value: 1, color: "#f1e05a" },
  { label: "Verilog", value: 1, color: "#b2b7f8" },
  { label: "Go", value: 1, color: "#00ADD8" },
  { label: "Others", value: 1, color: "#ccc" },
];

export const userData = {
  login: "ry",
  id: 80,
  node_id: "MDQ6VXNlcjgw",
  avatar_url: "https://avatars1.githubusercontent.com/u/80?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ry",
  html_url: "https://github.com/ry",
  followers_url: "https://api.github.com/users/ry/followers",
  following_url: "https://api.github.com/users/ry/following{/other_user}",
  gists_url: "https://api.github.com/users/ry/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ry/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ry/subscriptions",
  organizations_url: "https://api.github.com/users/ry/orgs",
  repos_url: "https://api.github.com/users/ry/repos",
  events_url: "https://api.github.com/users/ry/events{/privacy}",
  received_events_url: "https://api.github.com/users/ry/received_events",
  type: "User",
  site_admin: false,
  name: "Ryan Dahl",
  company: "@denoland ",
  blog: "http://tinyclouds.org/",
  location: "New York City",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 36,
  public_gists: 301,
  followers: 21589,
  following: 37,
  created_at: "2008-01-29T08:50:34Z",
  updated_at: "2020-06-06T13:08:39Z",
};

export const reposData = [
  {
    id: 164223619,
    node_id: "MDEwOlJlcG9zaXRvcnkxNjQyMjM2MTk=",
    name: "awesome-deno",
    full_name: "ry/awesome-deno",
    private: false,
    owner: {
      login: "ry",
      id: 80,
      node_id: "MDQ6VXNlcjgw",
      avatar_url: "https://avatars1.githubusercontent.com/u/80?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ry",
      html_url: "https://github.com/ry",
      followers_url: "https://api.github.com/users/ry/followers",
      following_url: "https://api.github.com/users/ry/following{/other_user}",
      gists_url: "https://api.github.com/users/ry/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ry/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ry/subscriptions",
      organizations_url: "https://api.github.com/users/ry/orgs",
      repos_url: "https://api.github.com/users/ry/repos",
      events_url: "https://api.github.com/users/ry/events{/privacy}",
      received_events_url: "https://api.github.com/users/ry/received_events",
      type: "User",
      site_admin: false,
    },
    html_url: "https://github.com/ry/awesome-deno",
    description: "🎉A curated list of awesome things related to Deno",
    fork: false,
    url: "https://api.github.com/repos/ry/awesome-deno",
    forks_url: "https://api.github.com/repos/ry/awesome-deno/forks",
    keys_url: "https://api.github.com/repos/ry/awesome-deno/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/ry/awesome-deno/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/ry/awesome-deno/teams",
    hooks_url: "https://api.github.com/repos/ry/awesome-deno/hooks",
    issue_events_url:
      "https://api.github.com/repos/ry/awesome-deno/issues/events{/number}",
    events_url: "https://api.github.com/repos/ry/awesome-deno/events",
    assignees_url:
      "https://api.github.com/repos/ry/awesome-deno/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/ry/awesome-deno/branches{/branch}",
    tags_url: "https://api.github.com/repos/ry/awesome-deno/tags",
    blobs_url: "https://api.github.com/repos/ry/awesome-deno/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/ry/awesome-deno/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/ry/awesome-deno/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/ry/awesome-deno/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/ry/awesome-deno/statuses/{sha}",
    languages_url: "https://api.github.com/repos/ry/awesome-deno/languages",
    stargazers_url: "https://api.github.com/repos/ry/awesome-deno/stargazers",
    contributors_url:
      "https://api.github.com/repos/ry/awesome-deno/contributors",
    subscribers_url: "https://api.github.com/repos/ry/awesome-deno/subscribers",
    subscription_url:
      "https://api.github.com/repos/ry/awesome-deno/subscription",
    commits_url: "https://api.github.com/repos/ry/awesome-deno/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/ry/awesome-deno/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/ry/awesome-deno/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/ry/awesome-deno/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/ry/awesome-deno/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/ry/awesome-deno/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/ry/awesome-deno/merges",
    archive_url:
      "https://api.github.com/repos/ry/awesome-deno/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/ry/awesome-deno/downloads",
    issues_url: "https://api.github.com/repos/ry/awesome-deno/issues{/number}",
    pulls_url: "https://api.github.com/repos/ry/awesome-deno/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/ry/awesome-deno/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/ry/awesome-deno/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/ry/awesome-deno/labels{/name}",
    releases_url: "https://api.github.com/repos/ry/awesome-deno/releases{/id}",
    deployments_url: "https://api.github.com/repos/ry/awesome-deno/deployments",
    created_at: "2019-01-05T14:47:49Z",
    updated_at: "2020-05-21T11:54:35Z",
    pushed_at: "2019-01-10T18:47:25Z",
    git_url: "git://github.com/ry/awesome-deno.git",
    ssh_url: "git@github.com:ry/awesome-deno.git",
    clone_url: "https://github.com/ry/awesome-deno.git",
    svn_url: "https://github.com/ry/awesome-deno",
    homepage: "",
    size: 1069,
    stargazers_count: 13,
    watchers_count: 13,
    language: null,
    has_issues: false,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    forks: 0,
    open_issues: 0,
    watchers: 13,
    default_branch: "master",
  },
  {
    id: 205937462,
    node_id: "MDEwOlJlcG9zaXRvcnkyMDU5Mzc0NjI=",
    name: "aws-appsync-chat",
    full_name: "ry/aws-appsync-chat",
    private: false,
    owner: {
      login: "ry",
      id: 80,
      node_id: "MDQ6VXNlcjgw",
      avatar_url: "https://avatars1.githubusercontent.com/u/80?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ry",
      html_url: "https://github.com/ry",
      followers_url: "https://api.github.com/users/ry/followers",
      following_url: "https://api.github.com/users/ry/following{/other_user}",
      gists_url: "https://api.github.com/users/ry/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ry/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ry/subscriptions",
      organizations_url: "https://api.github.com/users/ry/orgs",
      repos_url: "https://api.github.com/users/ry/repos",
      events_url: "https://api.github.com/users/ry/events{/privacy}",
      received_events_url: "https://api.github.com/users/ry/received_events",
      type: "User",
      site_admin: false,
    },
    html_url: "https://github.com/ry/aws-appsync-chat",
    description:
      "Real-Time Offline Ready Chat App written with GraphQL, AWS AppSync, & AWS Amplify",
    fork: false,
    url: "https://api.github.com/repos/ry/aws-appsync-chat",
    forks_url: "https://api.github.com/repos/ry/aws-appsync-chat/forks",
    keys_url: "https://api.github.com/repos/ry/aws-appsync-chat/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/ry/aws-appsync-chat/teams",
    hooks_url: "https://api.github.com/repos/ry/aws-appsync-chat/hooks",
    issue_events_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/issues/events{/number}",
    events_url: "https://api.github.com/repos/ry/aws-appsync-chat/events",
    assignees_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/branches{/branch}",
    tags_url: "https://api.github.com/repos/ry/aws-appsync-chat/tags",
    blobs_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/git/blobs{/sha}",
    git_tags_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/git/tags{/sha}",
    git_refs_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/git/refs{/sha}",
    trees_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/git/trees{/sha}",
    statuses_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/statuses/{sha}",
    languages_url: "https://api.github.com/repos/ry/aws-appsync-chat/languages",
    stargazers_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/stargazers",
    contributors_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/contributors",
    subscribers_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/subscribers",
    subscription_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/subscription",
    commits_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/ry/aws-appsync-chat/merges",
    archive_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/ry/aws-appsync-chat/downloads",
    issues_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/issues{/number}",
    pulls_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/notifications{?since,all,participating}",
    labels_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/labels{/name}",
    releases_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/releases{/id}",
    deployments_url:
      "https://api.github.com/repos/ry/aws-appsync-chat/deployments",
    created_at: "2019-09-02T21:13:07Z",
    updated_at: "2020-05-18T04:44:29Z",
    pushed_at: "2019-09-02T21:26:50Z",
    git_url: "git://github.com/ry/aws-appsync-chat.git",
    ssh_url: "git@github.com:ry/aws-appsync-chat.git",
    clone_url: "https://github.com/ry/aws-appsync-chat.git",
    svn_url: "https://github.com/ry/aws-appsync-chat",
    homepage: null,
    size: 426,
    stargazers_count: 8,
    watchers_count: 8,
    language: "JavaScript",
    has_issues: false,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    forks_count: 2,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: {
      key: "apache-2.0",
      name: "Apache License 2.0",
      spdx_id: "Apache-2.0",
      url: "https://api.github.com/licenses/apache-2.0",
      node_id: "MDc6TGljZW5zZTI=",
    },
    forks: 2,
    open_issues: 0,
    watchers: 8,
    default_branch: "master",
  },
  {
    id: 146788128,
    node_id: "MDEwOlJlcG9zaXRvcnkxNDY3ODgxMjg=",
    name: "deno",
    full_name: "ry/deno",
    private: false,
    owner: {
      login: "ry",
      id: 80,
      node_id: "MDQ6VXNlcjgw",
      avatar_url: "https://avatars1.githubusercontent.com/u/80?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ry",
      html_url: "https://github.com/ry",
      followers_url: "https://api.github.com/users/ry/followers",
      following_url: "https://api.github.com/users/ry/following{/other_user}",
      gists_url: "https://api.github.com/users/ry/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ry/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ry/subscriptions",
      organizations_url: "https://api.github.com/users/ry/orgs",
      repos_url: "https://api.github.com/users/ry/repos",
      events_url: "https://api.github.com/users/ry/events{/privacy}",
      received_events_url: "https://api.github.com/users/ry/received_events",
      type: "User",
      site_admin: false,
    },
    html_url: "https://github.com/ry/deno",
    description: null,
    fork: true,
    url: "https://api.github.com/repos/ry/deno",
    forks_url: "https://api.github.com/repos/ry/deno/forks",
    keys_url: "https://api.github.com/repos/ry/deno/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/ry/deno/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/ry/deno/teams",
    hooks_url: "https://api.github.com/repos/ry/deno/hooks",
    issue_events_url:
      "https://api.github.com/repos/ry/deno/issues/events{/number}",
    events_url: "https://api.github.com/repos/ry/deno/events",
    assignees_url: "https://api.github.com/repos/ry/deno/assignees{/user}",
    branches_url: "https://api.github.com/repos/ry/deno/branches{/branch}",
    tags_url: "https://api.github.com/repos/ry/deno/tags",
    blobs_url: "https://api.github.com/repos/ry/deno/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/ry/deno/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/ry/deno/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/ry/deno/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/ry/deno/statuses/{sha}",
    languages_url: "https://api.github.com/repos/ry/deno/languages",
    stargazers_url: "https://api.github.com/repos/ry/deno/stargazers",
    contributors_url: "https://api.github.com/repos/ry/deno/contributors",
    subscribers_url: "https://api.github.com/repos/ry/deno/subscribers",
    subscription_url: "https://api.github.com/repos/ry/deno/subscription",
    commits_url: "https://api.github.com/repos/ry/deno/commits{/sha}",
    git_commits_url: "https://api.github.com/repos/ry/deno/git/commits{/sha}",
    comments_url: "https://api.github.com/repos/ry/deno/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/ry/deno/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/ry/deno/contents/{+path}",
    compare_url: "https://api.github.com/repos/ry/deno/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/ry/deno/merges",
    archive_url: "https://api.github.com/repos/ry/deno/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/ry/deno/downloads",
    issues_url: "https://api.github.com/repos/ry/deno/issues{/number}",
    pulls_url: "https://api.github.com/repos/ry/deno/pulls{/number}",
    milestones_url: "https://api.github.com/repos/ry/deno/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/ry/deno/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/ry/deno/labels{/name}",
    releases_url: "https://api.github.com/repos/ry/deno/releases{/id}",
    deployments_url: "https://api.github.com/repos/ry/deno/deployments",
    created_at: "2018-08-30T18:09:18Z",
    updated_at: "2020-06-06T23:39:39Z",
    pushed_at: "2020-06-06T17:38:14Z",
    git_url: "git://github.com/ry/deno.git",
    ssh_url: "git@github.com:ry/deno.git",
    clone_url: "https://github.com/ry/deno.git",
    svn_url: "https://github.com/ry/deno",
    homepage: "https://github.com/denoland/deno",
    size: 17555,
    stargazers_count: 355,
    watchers_count: 355,
    language: "TypeScript",
    has_issues: false,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    forks_count: 29,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    forks: 29,
    open_issues: 0,
    watchers: 355,
    default_branch: "ry_master",
  },
  {
    id: 162363037,
    node_id: "MDEwOlJlcG9zaXRvcnkxNjIzNjMwMzc=",
    name: "deno_std",
    full_name: "ry/deno_std",
    private: false,
    owner: {
      login: "ry",
      id: 80,
      node_id: "MDQ6VXNlcjgw",
      avatar_url: "https://avatars1.githubusercontent.com/u/80?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ry",
      html_url: "https://github.com/ry",
      followers_url: "https://api.github.com/users/ry/followers",
      following_url: "https://api.github.com/users/ry/following{/other_user}",
      gists_url: "https://api.github.com/users/ry/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ry/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ry/subscriptions",
      organizations_url: "https://api.github.com/users/ry/orgs",
      repos_url: "https://api.github.com/users/ry/repos",
      events_url: "https://api.github.com/users/ry/events{/privacy}",
      received_events_url: "https://api.github.com/users/ry/received_events",
      type: "User",
      site_admin: false,
    },
    html_url: "https://github.com/ry/deno_std",
    description: "deno standard modules",
    fork: true,
    url: "https://api.github.com/repos/ry/deno_std",
    forks_url: "https://api.github.com/repos/ry/deno_std/forks",
    keys_url: "https://api.github.com/repos/ry/deno_std/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/ry/deno_std/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/ry/deno_std/teams",
    hooks_url: "https://api.github.com/repos/ry/deno_std/hooks",
    issue_events_url:
      "https://api.github.com/repos/ry/deno_std/issues/events{/number}",
    events_url: "https://api.github.com/repos/ry/deno_std/events",
    assignees_url: "https://api.github.com/repos/ry/deno_std/assignees{/user}",
    branches_url: "https://api.github.com/repos/ry/deno_std/branches{/branch}",
    tags_url: "https://api.github.com/repos/ry/deno_std/tags",
    blobs_url: "https://api.github.com/repos/ry/deno_std/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/ry/deno_std/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/ry/deno_std/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/ry/deno_std/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/ry/deno_std/statuses/{sha}",
    languages_url: "https://api.github.com/repos/ry/deno_std/languages",
    stargazers_url: "https://api.github.com/repos/ry/deno_std/stargazers",
    contributors_url: "https://api.github.com/repos/ry/deno_std/contributors",
    subscribers_url: "https://api.github.com/repos/ry/deno_std/subscribers",
    subscription_url: "https://api.github.com/repos/ry/deno_std/subscription",
    commits_url: "https://api.github.com/repos/ry/deno_std/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/ry/deno_std/git/commits{/sha}",
    comments_url: "https://api.github.com/repos/ry/deno_std/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/ry/deno_std/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/ry/deno_std/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/ry/deno_std/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/ry/deno_std/merges",
    archive_url:
      "https://api.github.com/repos/ry/deno_std/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/ry/deno_std/downloads",
    issues_url: "https://api.github.com/repos/ry/deno_std/issues{/number}",
    pulls_url: "https://api.github.com/repos/ry/deno_std/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/ry/deno_std/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/ry/deno_std/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/ry/deno_std/labels{/name}",
    releases_url: "https://api.github.com/repos/ry/deno_std/releases{/id}",
    deployments_url: "https://api.github.com/repos/ry/deno_std/deployments",
    created_at: "2018-12-19T00:55:46Z",
    updated_at: "2020-02-20T14:41:48Z",
    pushed_at: "2019-10-10T09:36:08Z",
    git_url: "git://github.com/ry/deno_std.git",
    ssh_url: "git@github.com:ry/deno_std.git",
    clone_url: "https://github.com/ry/deno_std.git",
    svn_url: "https://github.com/ry/deno_std",
    homepage: "https://deno.land/x/",
    size: 2109,
    stargazers_count: 2,
    watchers_count: 2,
    language: "TypeScript",
    has_issues: false,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    forks: 0,
    open_issues: 0,
    watchers: 2,
    default_branch: "master",
  },
  {
    id: 201152585,
    node_id: "MDEwOlJlcG9zaXRvcnkyMDExNTI1ODU=",
    name: "deno_typescript",
    full_name: "ry/deno_typescript",
    private: false,
    owner: {
      login: "ry",
      id: 80,
      node_id: "MDQ6VXNlcjgw",
      avatar_url: "https://avatars1.githubusercontent.com/u/80?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ry",
      html_url: "https://github.com/ry",
      followers_url: "https://api.github.com/users/ry/followers",
      following_url: "https://api.github.com/users/ry/following{/other_user}",
      gists_url: "https://api.github.com/users/ry/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ry/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ry/subscriptions",
      organizations_url: "https://api.github.com/users/ry/orgs",
      repos_url: "https://api.github.com/users/ry/repos",
      events_url: "https://api.github.com/users/ry/events{/privacy}",
      received_events_url: "https://api.github.com/users/ry/received_events",
      type: "User",
      site_admin: false,
    },
    html_url: "https://github.com/ry/deno_typescript",
    description: "To generate snapshots of TypeScript files during build.rs",
    fork: false,
    url: "https://api.github.com/repos/ry/deno_typescript",
    forks_url: "https://api.github.com/repos/ry/deno_typescript/forks",
    keys_url: "https://api.github.com/repos/ry/deno_typescript/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/ry/deno_typescript/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/ry/deno_typescript/teams",
    hooks_url: "https://api.github.com/repos/ry/deno_typescript/hooks",
    issue_events_url:
      "https://api.github.com/repos/ry/deno_typescript/issues/events{/number}",
    events_url: "https://api.github.com/repos/ry/deno_typescript/events",
    assignees_url:
      "https://api.github.com/repos/ry/deno_typescript/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/ry/deno_typescript/branches{/branch}",
    tags_url: "https://api.github.com/repos/ry/deno_typescript/tags",
    blobs_url:
      "https://api.github.com/repos/ry/deno_typescript/git/blobs{/sha}",
    git_tags_url:
      "https://api.github.com/repos/ry/deno_typescript/git/tags{/sha}",
    git_refs_url:
      "https://api.github.com/repos/ry/deno_typescript/git/refs{/sha}",
    trees_url:
      "https://api.github.com/repos/ry/deno_typescript/git/trees{/sha}",
    statuses_url:
      "https://api.github.com/repos/ry/deno_typescript/statuses/{sha}",
    languages_url: "https://api.github.com/repos/ry/deno_typescript/languages",
    stargazers_url:
      "https://api.github.com/repos/ry/deno_typescript/stargazers",
    contributors_url:
      "https://api.github.com/repos/ry/deno_typescript/contributors",
    subscribers_url:
      "https://api.github.com/repos/ry/deno_typescript/subscribers",
    subscription_url:
      "https://api.github.com/repos/ry/deno_typescript/subscription",
    commits_url:
      "https://api.github.com/repos/ry/deno_typescript/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/ry/deno_typescript/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/ry/deno_typescript/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/ry/deno_typescript/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/ry/deno_typescript/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/ry/deno_typescript/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/ry/deno_typescript/merges",
    archive_url:
      "https://api.github.com/repos/ry/deno_typescript/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/ry/deno_typescript/downloads",
    issues_url:
      "https://api.github.com/repos/ry/deno_typescript/issues{/number}",
    pulls_url: "https://api.github.com/repos/ry/deno_typescript/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/ry/deno_typescript/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/ry/deno_typescript/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/ry/deno_typescript/labels{/name}",
    releases_url:
      "https://api.github.com/repos/ry/deno_typescript/releases{/id}",
    deployments_url:
      "https://api.github.com/repos/ry/deno_typescript/deployments",
    created_at: "2019-08-08T01:14:41Z",
    updated_at: "2020-05-15T11:39:13Z",
    pushed_at: "2019-09-10T17:57:48Z",
    git_url: "git://github.com/ry/deno_typescript.git",
    ssh_url: "git@github.com:ry/deno_typescript.git",
    clone_url: "https://github.com/ry/deno_typescript.git",
    svn_url: "https://github.com/ry/deno_typescript",
    homepage: "",
    size: 4833,
    stargazers_count: 31,
    watchers_count: 31,
    language: "JavaScript",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 1,
    mirror_url: null,
    archived: true,
    disabled: false,
    open_issues_count: 0,
    license: null,
    forks: 1,
    open_issues: 0,
    watchers: 31,
    default_branch: "master",
  },
  {
    id: 217404450,
    node_id: "MDEwOlJlcG9zaXRvcnkyMTc0MDQ0NTA=",
    name: "deno_website2",
    full_name: "ry/deno_website2",
    private: false,
    owner: {
      login: "ry",
      id: 80,
      node_id: "MDQ6VXNlcjgw",
      avatar_url: "https://avatars1.githubusercontent.com/u/80?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ry",
      html_url: "https://github.com/ry",
      followers_url: "https://api.github.com/users/ry/followers",
      following_url: "https://api.github.com/users/ry/following{/other_user}",
      gists_url: "https://api.github.com/users/ry/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ry/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ry/subscriptions",
      organizations_url: "https://api.github.com/users/ry/orgs",
      repos_url: "https://api.github.com/users/ry/repos",
      events_url: "https://api.github.com/users/ry/events{/privacy}",
      received_events_url: "https://api.github.com/users/ry/received_events",
      type: "User",
      site_admin: false,
    },
    html_url: "https://github.com/ry/deno_website2",
    description: "prototype of new deno.land website ",
    fork: true,
    url: "https://api.github.com/repos/ry/deno_website2",
    forks_url: "https://api.github.com/repos/ry/deno_website2/forks",
    keys_url: "https://api.github.com/repos/ry/deno_website2/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/ry/deno_website2/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/ry/deno_website2/teams",
    hooks_url: "https://api.github.com/repos/ry/deno_website2/hooks",
    issue_events_url:
      "https://api.github.com/repos/ry/deno_website2/issues/events{/number}",
    events_url: "https://api.github.com/repos/ry/deno_website2/events",
    assignees_url:
      "https://api.github.com/repos/ry/deno_website2/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/ry/deno_website2/branches{/branch}",
    tags_url: "https://api.github.com/repos/ry/deno_website2/tags",
    blobs_url: "https://api.github.com/repos/ry/deno_website2/git/blobs{/sha}",
    git_tags_url:
      "https://api.github.com/repos/ry/deno_website2/git/tags{/sha}",
    git_refs_url:
      "https://api.github.com/repos/ry/deno_website2/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/ry/deno_website2/git/trees{/sha}",
    statuses_url:
      "https://api.github.com/repos/ry/deno_website2/statuses/{sha}",
    languages_url: "https://api.github.com/repos/ry/deno_website2/languages",
    stargazers_url: "https://api.github.com/repos/ry/deno_website2/stargazers",
    contributors_url:
      "https://api.github.com/repos/ry/deno_website2/contributors",
    subscribers_url:
      "https://api.github.com/repos/ry/deno_website2/subscribers",
    subscription_url:
      "https://api.github.com/repos/ry/deno_website2/subscription",
    commits_url: "https://api.github.com/repos/ry/deno_website2/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/ry/deno_website2/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/ry/deno_website2/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/ry/deno_website2/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/ry/deno_website2/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/ry/deno_website2/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/ry/deno_website2/merges",
    archive_url:
      "https://api.github.com/repos/ry/deno_website2/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/ry/deno_website2/downloads",
    issues_url: "https://api.github.com/repos/ry/deno_website2/issues{/number}",
    pulls_url: "https://api.github.com/repos/ry/deno_website2/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/ry/deno_website2/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/ry/deno_website2/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/ry/deno_website2/labels{/name}",
    releases_url: "https://api.github.com/repos/ry/deno_website2/releases{/id}",
    deployments_url:
      "https://api.github.com/repos/ry/deno_website2/deployments",
    created_at: "2019-10-24T22:14:58Z",
    updated_at: "2020-05-25T17:24:19Z",
    pushed_at: "2020-05-29T21:48:43Z",
    git_url: "git://github.com/ry/deno_website2.git",
    ssh_url: "git@github.com:ry/deno_website2.git",
    clone_url: "https://github.com/ry/deno_website2.git",
    svn_url: "https://github.com/ry/deno_website2",
    homepage: "https://denoland.netlify.com",
    size: 48505,
    stargazers_count: 8,
    watchers_count: 8,
    language: null,
    has_issues: false,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 1,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    forks: 1,
    open_issues: 0,
    watchers: 8,
    default_branch: "master",
  },
  {
    id: 248276811,
    node_id: "MDEwOlJlcG9zaXRvcnkyNDgyNzY4MTE=",
    name: "discord-open-source",
    full_name: "ry/discord-open-source",
    private: false,
    owner: {
      login: "ry",
      id: 80,
      node_id: "MDQ6VXNlcjgw",
      avatar_url: "https://avatars1.githubusercontent.com/u/80?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ry",
      html_url: "https://github.com/ry",
      followers_url: "https://api.github.com/users/ry/followers",
      following_url: "https://api.github.com/users/ry/following{/other_user}",
      gists_url: "https://api.github.com/users/ry/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ry/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ry/subscriptions",
      organizations_url: "https://api.github.com/users/ry/orgs",
      repos_url: "https://api.github.com/users/ry/repos",
      events_url: "https://api.github.com/users/ry/events{/privacy}",
      received_events_url: "https://api.github.com/users/ry/received_events",
      type: "User",
      site_admin: false,
    },
    html_url: "https://github.com/ry/discord-open-source",
    description: "List of open source communities living on Discord",
    fork: true,
    url: "https://api.github.com/repos/ry/discord-open-source",
    forks_url: "https://api.github.com/repos/ry/discord-open-source/forks",
    keys_url:
      "https://api.github.com/repos/ry/discord-open-source/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/ry/discord-open-source/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/ry/discord-open-source/teams",
    hooks_url: "https://api.github.com/repos/ry/discord-open-source/hooks",
    issue_events_url:
      "https://api.github.com/repos/ry/discord-open-source/issues/events{/number}",
    events_url: "https://api.github.com/repos/ry/discord-open-source/events",
    assignees_url:
      "https://api.github.com/repos/ry/discord-open-source/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/ry/discord-open-source/branches{/branch}",
    tags_url: "https://api.github.com/repos/ry/discord-open-source/tags",
    blobs_url:
      "https://api.github.com/repos/ry/discord-open-source/git/blobs{/sha}",
    git_tags_url:
      "https://api.github.com/repos/ry/discord-open-source/git/tags{/sha}",
    git_refs_url:
      "https://api.github.com/repos/ry/discord-open-source/git/refs{/sha}",
    trees_url:
      "https://api.github.com/repos/ry/discord-open-source/git/trees{/sha}",
    statuses_url:
      "https://api.github.com/repos/ry/discord-open-source/statuses/{sha}",
    languages_url:
      "https://api.github.com/repos/ry/discord-open-source/languages",
    stargazers_url:
      "https://api.github.com/repos/ry/discord-open-source/stargazers",
    contributors_url:
      "https://api.github.com/repos/ry/discord-open-source/contributors",
    subscribers_url:
      "https://api.github.com/repos/ry/discord-open-source/subscribers",
    subscription_url:
      "https://api.github.com/repos/ry/discord-open-source/subscription",
    commits_url:
      "https://api.github.com/repos/ry/discord-open-source/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/ry/discord-open-source/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/ry/discord-open-source/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/ry/discord-open-source/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/ry/discord-open-source/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/ry/discord-open-source/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/ry/discord-open-source/merges",
    archive_url:
      "https://api.github.com/repos/ry/discord-open-source/{archive_format}{/ref}",
    downloads_url:
      "https://api.github.com/repos/ry/discord-open-source/downloads",
    issues_url:
      "https://api.github.com/repos/ry/discord-open-source/issues{/number}",
    pulls_url:
      "https://api.github.com/repos/ry/discord-open-source/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/ry/discord-open-source/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/ry/discord-open-source/notifications{?since,all,participating}",
    labels_url:
      "https://api.github.com/repos/ry/discord-open-source/labels{/name}",
    releases_url:
      "https://api.github.com/repos/ry/discord-open-source/releases{/id}",
    deployments_url:
      "https://api.github.com/repos/ry/discord-open-source/deployments",
    created_at: "2020-03-18T15:55:29Z",
    updated_at: "2020-05-14T00:20:54Z",
    pushed_at: "2020-03-18T15:56:18Z",
    git_url: "git://github.com/ry/discord-open-source.git",
    ssh_url: "git@github.com:ry/discord-open-source.git",
    clone_url: "https://github.com/ry/discord-open-source.git",
    svn_url: "https://github.com/ry/discord-open-source",
    homepage: null,
    size: 1779,
    stargazers_count: 1,
    watchers_count: 1,
    language: null,
    has_issues: false,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    forks: 0,
    open_issues: 0,
    watchers: 1,
    default_branch: "master",
  },
  {
    id: 237802090,
    node_id: "MDEwOlJlcG9zaXRvcnkyMzc4MDIwOTA=",
    name: "eecs151",
    full_name: "ry/eecs151",
    private: false,
    owner: {
      login: "ry",
      id: 80,
      node_id: "MDQ6VXNlcjgw",
      avatar_url: "https://avatars1.githubusercontent.com/u/80?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ry",
      html_url: "https://github.com/ry",
      followers_url: "https://api.github.com/users/ry/followers",
      following_url: "https://api.github.com/users/ry/following{/other_user}",
      gists_url: "https://api.github.com/users/ry/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ry/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ry/subscriptions",
      organizations_url: "https://api.github.com/users/ry/orgs",
      repos_url: "https://api.github.com/users/ry/repos",
      events_url: "https://api.github.com/users/ry/events{/privacy}",
      received_events_url: "https://api.github.com/users/ry/received_events",
      type: "User",
      site_admin: false,
    },
    html_url: "https://github.com/ry/eecs151",
    description: "http://inst.eecs.berkeley.edu/~eecs151/fa19/",
    fork: false,
    url: "https://api.github.com/repos/ry/eecs151",
    forks_url: "https://api.github.com/repos/ry/eecs151/forks",
    keys_url: "https://api.github.com/repos/ry/eecs151/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/ry/eecs151/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/ry/eecs151/teams",
    hooks_url: "https://api.github.com/repos/ry/eecs151/hooks",
    issue_events_url:
      "https://api.github.com/repos/ry/eecs151/issues/events{/number}",
    events_url: "https://api.github.com/repos/ry/eecs151/events",
    assignees_url: "https://api.github.com/repos/ry/eecs151/assignees{/user}",
    branches_url: "https://api.github.com/repos/ry/eecs151/branches{/branch}",
    tags_url: "https://api.github.com/repos/ry/eecs151/tags",
    blobs_url: "https://api.github.com/repos/ry/eecs151/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/ry/eecs151/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/ry/eecs151/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/ry/eecs151/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/ry/eecs151/statuses/{sha}",
    languages_url: "https://api.github.com/repos/ry/eecs151/languages",
    stargazers_url: "https://api.github.com/repos/ry/eecs151/stargazers",
    contributors_url: "https://api.github.com/repos/ry/eecs151/contributors",
    subscribers_url: "https://api.github.com/repos/ry/eecs151/subscribers",
    subscription_url: "https://api.github.com/repos/ry/eecs151/subscription",
    commits_url: "https://api.github.com/repos/ry/eecs151/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/ry/eecs151/git/commits{/sha}",
    comments_url: "https://api.github.com/repos/ry/eecs151/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/ry/eecs151/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/ry/eecs151/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/ry/eecs151/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/ry/eecs151/merges",
    archive_url:
      "https://api.github.com/repos/ry/eecs151/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/ry/eecs151/downloads",
    issues_url: "https://api.github.com/repos/ry/eecs151/issues{/number}",
    pulls_url: "https://api.github.com/repos/ry/eecs151/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/ry/eecs151/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/ry/eecs151/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/ry/eecs151/labels{/name}",
    releases_url: "https://api.github.com/repos/ry/eecs151/releases{/id}",
    deployments_url: "https://api.github.com/repos/ry/eecs151/deployments",
    created_at: "2020-02-02T16:43:05Z",
    updated_at: "2020-02-20T14:41:44Z",
    pushed_at: "2020-02-02T16:53:03Z",
    git_url: "git://github.com/ry/eecs151.git",
    ssh_url: "git@github.com:ry/eecs151.git",
    clone_url: "https://github.com/ry/eecs151.git",
    svn_url: "https://github.com/ry/eecs151",
    homepage: null,
    size: 3,
    stargazers_count: 12,
    watchers_count: 12,
    language: "Verilog",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    forks: 0,
    open_issues: 0,
    watchers: 12,
    default_branch: "master",
  },
  {
    id: 151741813,
    node_id: "MDEwOlJlcG9zaXRvcnkxNTE3NDE4MTM=",
    name: "flatbuffers",
    full_name: "ry/flatbuffers",
    private: false,
    owner: {
      login: "ry",
      id: 80,
      node_id: "MDQ6VXNlcjgw",
      avatar_url: "https://avatars1.githubusercontent.com/u/80?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ry",
      html_url: "https://github.com/ry",
      followers_url: "https://api.github.com/users/ry/followers",
      following_url: "https://api.github.com/users/ry/following{/other_user}",
      gists_url: "https://api.github.com/users/ry/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ry/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ry/subscriptions",
      organizations_url: "https://api.github.com/users/ry/orgs",
      repos_url: "https://api.github.com/users/ry/repos",
      events_url: "https://api.github.com/users/ry/events{/privacy}",
      received_events_url: "https://api.github.com/users/ry/received_events",
      type: "User",
      site_admin: false,
    },
    html_url: "https://github.com/ry/flatbuffers",
    description: "Memory Efficient Serialization Library",
    fork: true,
    url: "https://api.github.com/repos/ry/flatbuffers",
    forks_url: "https://api.github.com/repos/ry/flatbuffers/forks",
    keys_url: "https://api.github.com/repos/ry/flatbuffers/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/ry/flatbuffers/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/ry/flatbuffers/teams",
    hooks_url: "https://api.github.com/repos/ry/flatbuffers/hooks",
    issue_events_url:
      "https://api.github.com/repos/ry/flatbuffers/issues/events{/number}",
    events_url: "https://api.github.com/repos/ry/flatbuffers/events",
    assignees_url:
      "https://api.github.com/repos/ry/flatbuffers/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/ry/flatbuffers/branches{/branch}",
    tags_url: "https://api.github.com/repos/ry/flatbuffers/tags",
    blobs_url: "https://api.github.com/repos/ry/flatbuffers/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/ry/flatbuffers/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/ry/flatbuffers/git/refs{/sha}",
    trees_url: "https://api.github.com/repos/ry/flatbuffers/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/ry/flatbuffers/statuses/{sha}",
    languages_url: "https://api.github.com/repos/ry/flatbuffers/languages",
    stargazers_url: "https://api.github.com/repos/ry/flatbuffers/stargazers",
    contributors_url:
      "https://api.github.com/repos/ry/flatbuffers/contributors",
    subscribers_url: "https://api.github.com/repos/ry/flatbuffers/subscribers",
    subscription_url:
      "https://api.github.com/repos/ry/flatbuffers/subscription",
    commits_url: "https://api.github.com/repos/ry/flatbuffers/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/ry/flatbuffers/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/ry/flatbuffers/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/ry/flatbuffers/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/ry/flatbuffers/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/ry/flatbuffers/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/ry/flatbuffers/merges",
    archive_url:
      "https://api.github.com/repos/ry/flatbuffers/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/ry/flatbuffers/downloads",
    issues_url: "https://api.github.com/repos/ry/flatbuffers/issues{/number}",
    pulls_url: "https://api.github.com/repos/ry/flatbuffers/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/ry/flatbuffers/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/ry/flatbuffers/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/ry/flatbuffers/labels{/name}",
    releases_url: "https://api.github.com/repos/ry/flatbuffers/releases{/id}",
    deployments_url: "https://api.github.com/repos/ry/flatbuffers/deployments",
    created_at: "2018-10-05T15:31:17Z",
    updated_at: "2020-02-20T14:42:01Z",
    pushed_at: "2018-10-05T15:35:03Z",
    git_url: "git://github.com/ry/flatbuffers.git",
    ssh_url: "git@github.com:ry/flatbuffers.git",
    clone_url: "https://github.com/ry/flatbuffers.git",
    svn_url: "https://github.com/ry/flatbuffers",
    homepage: "http://google.github.io/flatbuffers/",
    size: 7438,
    stargazers_count: 2,
    watchers_count: 2,
    language: "C++",
    has_issues: false,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    forks_count: 1,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: {
      key: "apache-2.0",
      name: "Apache License 2.0",
      spdx_id: "Apache-2.0",
      url: "https://api.github.com/licenses/apache-2.0",
      node_id: "MDc6TGljZW5zZTI=",
    },
    forks: 1,
    open_issues: 0,
    watchers: 2,
    default_branch: "master",
  },
  {
    id: 138584245,
    node_id: "MDEwOlJlcG9zaXRvcnkxMzg1ODQyNDU=",
    name: "flatbuffers_chromium",
    full_name: "ry/flatbuffers_chromium",
    private: false,
    owner: {
      login: "ry",
      id: 80,
      node_id: "MDQ6VXNlcjgw",
      avatar_url: "https://avatars1.githubusercontent.com/u/80?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ry",
      html_url: "https://github.com/ry",
      followers_url: "https://api.github.com/users/ry/followers",
      following_url: "https://api.github.com/users/ry/following{/other_user}",
      gists_url: "https://api.github.com/users/ry/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ry/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ry/subscriptions",
      organizations_url: "https://api.github.com/users/ry/orgs",
      repos_url: "https://api.github.com/users/ry/repos",
      events_url: "https://api.github.com/users/ry/events{/privacy}",
      received_events_url: "https://api.github.com/users/ry/received_events",
      type: "User",
      site_admin: false,
    },
    html_url: "https://github.com/ry/flatbuffers_chromium",
    description: null,
    fork: false,
    url: "https://api.github.com/repos/ry/flatbuffers_chromium",
    forks_url: "https://api.github.com/repos/ry/flatbuffers_chromium/forks",
    keys_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/keys{/key_id}",
    collaborators_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/ry/flatbuffers_chromium/teams",
    hooks_url: "https://api.github.com/repos/ry/flatbuffers_chromium/hooks",
    issue_events_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/issues/events{/number}",
    events_url: "https://api.github.com/repos/ry/flatbuffers_chromium/events",
    assignees_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/assignees{/user}",
    branches_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/branches{/branch}",
    tags_url: "https://api.github.com/repos/ry/flatbuffers_chromium/tags",
    blobs_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/git/blobs{/sha}",
    git_tags_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/git/tags{/sha}",
    git_refs_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/git/refs{/sha}",
    trees_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/git/trees{/sha}",
    statuses_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/statuses/{sha}",
    languages_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/languages",
    stargazers_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/stargazers",
    contributors_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/contributors",
    subscribers_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/subscribers",
    subscription_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/subscription",
    commits_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/commits{/sha}",
    git_commits_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/git/commits{/sha}",
    comments_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/comments{/number}",
    issue_comment_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/issues/comments{/number}",
    contents_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/contents/{+path}",
    compare_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/ry/flatbuffers_chromium/merges",
    archive_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/{archive_format}{/ref}",
    downloads_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/downloads",
    issues_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/issues{/number}",
    pulls_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/pulls{/number}",
    milestones_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/milestones{/number}",
    notifications_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/notifications{?since,all,participating}",
    labels_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/labels{/name}",
    releases_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/releases{/id}",
    deployments_url:
      "https://api.github.com/repos/ry/flatbuffers_chromium/deployments",
    created_at: "2018-06-25T11:13:22Z",
    updated_at: "2020-02-20T14:42:02Z",
    pushed_at: "2018-06-25T11:15:09Z",
    git_url: "git://github.com/ry/flatbuffers_chromium.git",
    ssh_url: "git@github.com:ry/flatbuffers_chromium.git",
    clone_url: "https://github.com/ry/flatbuffers_chromium.git",
    svn_url: "https://github.com/ry/flatbuffers_chromium",
    homepage: null,
    size: 5882,
    stargazers_count: 21,
    watchers_count: 21,
    language: "C++",
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 1,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: {
      key: "apache-2.0",
      name: "Apache License 2.0",
      spdx_id: "Apache-2.0",
      url: "https://api.github.com/licenses/apache-2.0",
      node_id: "MDc6TGljZW5zZTI=",
    },
    forks: 1,
    open_issues: 0,
    watchers: 21,
    default_branch: "master",
  },
];
